/**
 * Report Agent Node — IndianAPI Edition
 *
 * Responsibilities:
 * 1. Write the Executive Summary and Business Overview sections
 * 2. Compute the composite confidence score
 * 3. Compile all citations from all agent evidence
 * 4. Assemble the complete 10-section report
 * 5. Persist the report to PostgreSQL via PrismaService
 * 6. Emit complete event via SSE
 */

import { ChatGoogleGenerativeAI } from '@langchain/google-genai';
import { HumanMessage, SystemMessage } from '@langchain/core/messages';
import { ResearchState } from '../state/research-state';
import { formatCurrency } from '../tools/financial-calculator.tool';
import { invokeWithRetry, sanitizeJsonString } from '../tools/llm-helper';
import {
  ReportSection,
  ConfidenceScore,
  Citation,
  TokenUsage,
  Evidence,
  FinancialAgentOutput,
  NewsAgentOutput,
  CompetitiveAgentOutput,
  ThesisAgentOutput,
  AnalyzedArticle,
} from '../types/agent-types';
import { PrismaService } from '../../prisma/prisma.service';
import { v4 as uuidv4 } from 'uuid';

const FINANCIAL_DISCLAIMER =
  'This report is generated by an AI system and is for informational purposes only. It does not constitute financial advice, a recommendation, or an offer to buy or sell any security. Always consult with a qualified financial advisor before making investment decisions. Past performance is not indicative of future results. ResearchGPT — Portfolio Project.';

const EXECUTIVE_SUMMARY_PROMPT = `You are the Report Agent for ResearchGPT. Write the Executive Summary and Business Overview sections of an equity research report for an Indian company.

Return ONLY a valid JSON object:
{
  "executiveSummary": "## Executive Summary\\n\\n200-300 word comprehensive synthesis of the entire report...",
  "businessOverview": "## Business Overview\\n\\n150-200 word description of what the company does, its business model, key products/services, and market position..."
}

Be professional, concise, and evidence-backed. Include the investment recommendation and confidence score in the Executive Summary. Use Indian business context and ₹ (INR) format where appropriate.`;

export async function reportNode(
  state: ResearchState,
  prismaService?: PrismaService,
): Promise<Partial<ResearchState>> {
  const {
    runId,
    company,
    financialOutput,
    newsOutput,
    competitiveOutput,
    thesisOutput,
    evidence,
    sseEmitter,
  } = state;

  if (!company) {
    return { errors: ['Report agent: company not resolved'] };
  }

  sseEmitter?.next({
    event: 'phase',
    data: { phase: 'reporting', status: 'started', message: 'Assembling final report...' },
  });

  const llm = new ChatGoogleGenerativeAI({
    model: 'gemini-2.5-flash',
    apiKey: process.env.GCP_API_KEY!,
    temperature: 0.3,
    json: true,
  });

  const startTime = Date.now();

  try {
    // ---- Compute Confidence Score ----
    const confidenceScore = computeConfidenceScore(
      financialOutput,
      newsOutput,
      competitiveOutput,
      thesisOutput,
      evidence.length,
    );

    // ---- Compile Citations ----
    const citations = compileCitations(evidence, financialOutput, newsOutput, company);

    // ---- Generate Executive Summary + Business Overview ----
    sseEmitter?.next({
      event: 'progress',
      data: { agent: 'report', message: 'Writing executive summary...' },
    });

    const recommendation = thesisOutput?.investmentThesis?.recommendation ?? 'hold';
    const recommendationEmoji =
      { strong_buy: '🟢', buy: '🟩', hold: '🟡', sell: '🟠', strong_sell: '🔴' }[recommendation] ?? '⚪';

    const llmContext = `Company: ${company.companyName} (${company.ticker}) — ${company.exchange}
Sector: ${company.sector} | Industry: ${company.industry}

RECOMMENDATION: ${recommendationEmoji} ${recommendation.replace('_', ' ').toUpperCase()}
CONFIDENCE SCORE: ${confidenceScore.overall}/100
TIME HORIZON: ${thesisOutput?.investmentThesis?.timeHorizon?.replace('_', ' ') ?? '1 year'}

FINANCIAL SNAPSHOT:
- Price: ₹${financialOutput?.financialSummary.currentPrice ?? 'N/A'} | Market Cap: ${formatCurrency(financialOutput?.financialSummary.marketCap ?? 0, true)}
- P/E: ${financialOutput?.financialSummary.peRatio?.toFixed(1) ?? 'N/A'}
- Revenue Growth YoY: ${financialOutput?.derivedMetrics.revenueGrowthYoY != null ? `${financialOutput.derivedMetrics.revenueGrowthYoY.toFixed(1)}%` : 'N/A'}

NEWS SENTIMENT: ${newsOutput?.overallSentiment.label ?? 'N/A'}
COMPETITIVE MOAT: ${competitiveOutput?.moatAssessment.type ?? 'N/A'}

THESIS SUMMARY: ${thesisOutput?.investmentThesis?.summary ?? 'N/A'}

KEY BULL POINTS:
${thesisOutput?.bullCase.keyPoints.slice(0, 3).map((p) => `- ${p.argument}`).join('\n') ?? 'N/A'}

KEY BEAR RISKS:
${thesisOutput?.bearCase.keyPoints.slice(0, 3).map((p) => `- ${p.argument}`).join('\n') ?? 'N/A'}`;

    const llmResponse = await invokeWithRetry(llm, [
      new SystemMessage(EXECUTIVE_SUMMARY_PROMPT),
      new HumanMessage(llmContext),
    ]);

    const responseText = String(llmResponse.content);
    const jsonMatch = responseText.match(/\{[\s\S]*\}/);

    let executiveSummary = `## Executive Summary\n\n${company.companyName} (${company.ticker}) — ${recommendation.replace('_', ' ').toUpperCase()}\n\nReport generation encountered an issue with the executive summary.`;
    let businessOverview = `## Business Overview\n\n${company.companyName} is a company in the ${company.sector} sector.`;

    if (jsonMatch) {
      try {
        const sanitizedJson = sanitizeJsonString(jsonMatch[0]);
        const parsed = JSON.parse(sanitizedJson) as {
          executiveSummary: string;
          businessOverview: string;
        };
        executiveSummary = parsed.executiveSummary || executiveSummary;
        businessOverview = parsed.businessOverview || businessOverview;
      } catch {
        // Keep fallback content
      }
    }

    const tokenUsage: TokenUsage = {
      inputTokens: (llmResponse.usage_metadata?.input_tokens as number) ?? 0,
      outputTokens: (llmResponse.usage_metadata?.output_tokens as number) ?? 0,
      model: 'gemini-2.5-flash',
    };

    // ---- Build Confidence Score Section ----
    const confidenceMarkdown = buildConfidenceSectionMarkdown(
      confidenceScore,
      thesisOutput?.evidenceGaps ?? [],
    );

    // ---- Assemble Initial 9 Sections ----
    const sections: ReportSection[] = [
      {
        sectionId: 'executive_summary',
        title: 'Executive Summary',
        sectionOrder: 1,
        content: executiveSummary,
        generatedBy: 'report',
        hasDataGap: false,
      },
      {
        sectionId: 'business_overview',
        title: 'Business Overview',
        sectionOrder: 2,
        content: businessOverview,
        generatedBy: 'report',
        hasDataGap: false,
      },
      {
        sectionId: 'financial_analysis',
        title: 'Financial Analysis',
        sectionOrder: 3,
        content: financialOutput?.sectionMarkdown ?? '## Financial Analysis\n\nData not available.',
        generatedBy: 'financial',
        hasDataGap: financialOutput?.hasDataGap ?? true,
        inputTokens: financialOutput?.tokenUsage.inputTokens,
        outputTokens: financialOutput?.tokenUsage.outputTokens,
      },
      {
        sectionId: 'news_analysis',
        title: 'Recent News Analysis',
        sectionOrder: 4,
        content: newsOutput?.sectionMarkdown ?? '## Recent News Analysis\n\nData not available.',
        generatedBy: 'news',
        hasDataGap: newsOutput?.hasDataGap ?? true,
        inputTokens: newsOutput?.tokenUsage.inputTokens,
        outputTokens: newsOutput?.tokenUsage.outputTokens,
      },
      {
        sectionId: 'competitive_analysis',
        title: 'Competitive Analysis',
        sectionOrder: 5,
        content: competitiveOutput?.sectionMarkdown ?? '## Competitive Analysis\n\nData not available.',
        generatedBy: 'competitive',
        hasDataGap: competitiveOutput?.hasDataGap ?? true,
        inputTokens: competitiveOutput?.tokenUsage.inputTokens,
        outputTokens: competitiveOutput?.tokenUsage.outputTokens,
      },
      {
        sectionId: 'bull_case',
        title: `Bull Case: ${thesisOutput?.bullCase.title ?? ''}`,
        sectionOrder: 6,
        content: thesisOutput?.sectionMarkdown?.split('---')[0] ?? '## Bull Case\n\nData not available.',
        generatedBy: 'thesis',
        hasDataGap: !thesisOutput,
      },
      {
        sectionId: 'bear_case',
        title: `Bear Case: ${thesisOutput?.bearCase.title ?? ''}`,
        sectionOrder: 7,
        content: thesisOutput?.sectionMarkdown?.split('---')[1] ?? '## Bear Case\n\nData not available.',
        generatedBy: 'thesis',
        hasDataGap: !thesisOutput,
      },
      {
        sectionId: 'investment_thesis',
        title: 'Investment Thesis',
        sectionOrder: 8,
        content: thesisOutput?.sectionMarkdown?.split('---')[2] ?? '## Investment Thesis\n\nData not available.',
        generatedBy: 'thesis',
        hasDataGap: !thesisOutput,
        inputTokens: thesisOutput?.tokenUsage.inputTokens,
        outputTokens: thesisOutput?.tokenUsage.outputTokens,
      },
      {
        sectionId: 'confidence_score',
        title: 'Confidence Score & Data Quality',
        sectionOrder: 9,
        content: confidenceMarkdown,
        generatedBy: 'report',
        hasDataGap: false,
      },
    ];

    // ---- Align Citations in Section Markdown Contents ----
    sections.forEach((s) => {
      s.content = alignCitations(s.content, citations);
    });

    // ---- Build and Add Citations Section (using final aligned citations) ----
    const citationsMarkdown = buildCitationsSectionMarkdown(citations);
    sections.push({
      sectionId: 'citations',
      title: 'Source Citations',
      sectionOrder: 10,
      content: citationsMarkdown,
      generatedBy: 'report',
      hasDataGap: false,
    });

    // ---- Emit executive summary and business overview to frontend ----
    sseEmitter?.next({
      event: 'section',
      data: {
        sectionId: 'executive_summary',
        title: 'Executive Summary',
        content: sections.find((s) => s.sectionId === 'executive_summary')?.content || executiveSummary,
        order: 1,
      },
    });

    sseEmitter?.next({
      event: 'section',
      data: {
        sectionId: 'business_overview',
        title: 'Business Overview',
        content: sections.find((s) => s.sectionId === 'business_overview')?.content || businessOverview,
        order: 2,
      },
    });

    sseEmitter?.next({
      event: 'section',
      data: {
        sectionId: 'confidence_score',
        title: 'Confidence Score & Data Quality',
        content: sections.find((s) => s.sectionId === 'confidence_score')?.content || confidenceMarkdown,
        order: 9,
      },
    });

    sseEmitter?.next({
      event: 'section',
      data: {
        sectionId: 'citations',
        title: 'Source Citations',
        content: citationsMarkdown,
        order: 10,
      },
    });

    // ---- Persist to Database ----
    let reportId = uuidv4();
    const totalDurationMs = Date.now() - startTime;

    if (prismaService) {
      try {
        sseEmitter?.next({
          event: 'progress',
          data: { agent: 'report', message: 'Saving report to database...' },
        });

        // Compute total tokens
        const allOutputs = [financialOutput, newsOutput, competitiveOutput, thesisOutput].filter(Boolean);
        const totalInputTokens = allOutputs.reduce((sum, o) => sum + (o?.tokenUsage.inputTokens ?? 0), 0) + tokenUsage.inputTokens;
        const totalOutputTokens = allOutputs.reduce((sum, o) => sum + (o?.tokenUsage.outputTokens ?? 0), 0) + tokenUsage.outputTokens;

        // Create the report record
        const report = await prismaService.report.create({
          data: {
            runId,
            ticker: company.ticker,
            companyName: company.companyName,
            exchange: company.exchange,
            confidenceOverall: confidenceScore.overall,
            confidenceBreakdown: confidenceScore.breakdown as unknown as Record<string, number>,
            recommendation: thesisOutput?.investmentThesis.recommendation,
            totalInputTokens,
            totalOutputTokens,
            totalCostUsd: 0,
            generationTimeSeconds: totalDurationMs / 1000,
            modelsUsed: ['gemini-2.5-flash'],
            dataSourcesUsed: ['IndianAPI', 'Tavily', 'Exa'],
            disclaimer: FINANCIAL_DISCLAIMER,
            sections: {
              create: sections.map((s) => ({
                sectionId: s.sectionId,
                title: s.title,
                sectionOrder: s.sectionOrder,
                content: s.content,
                generatedBy: s.generatedBy,
                hasDataGap: s.hasDataGap,
                inputTokens: s.inputTokens,
                outputTokens: s.outputTokens,
              })),
            },
            citations: {
              create: citations.map((c) => ({
                displayId: c.displayId,
                title: c.title,
                sourceName: c.sourceName,
                url: c.url,
                citationType: c.citationType,
              })),
            },
          },
        });

        reportId = report.id;

        // Update the research run
        await prismaService.researchRun.update({
          where: { id: runId },
          data: {
            status: 'completed',
            ticker: company.ticker,
            companyName: company.companyName,
            exchange: company.exchange,
            sector: company.sector,
            industry: company.industry,
            completedAt: new Date(),
            totalDurationMs: Date.now() - startTime,
          },
        });

        console.log(`[Report] Persisted report ${reportId} for run ${runId}`);
      } catch (dbErr) {
        console.error('[Report] Database error:', dbErr);
      }
    }

    // ---- Emit complete event ----
    sseEmitter?.next({
      event: 'complete',
      data: {
        runId,
        reportId,
        confidenceScore: confidenceScore.overall,
        totalDurationMs: Date.now() - startTime,
        citationCount: citations.length,
      },
    });

    sseEmitter?.complete();

    console.log(
      `[Report] Completed for ${company.ticker} | Confidence: ${confidenceScore.overall} | Duration: ${(Date.now() - startTime) / 1000}s`,
    );

    return {
      reportSections: sections,
      confidenceScore,
      citations,
      reportId,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('[Report] Error:', message);

    // Update run as failed
    if (prismaService) {
      await prismaService.researchRun
        .update({
          where: { id: runId },
          data: { status: 'failed', errorMessage: message },
        })
        .catch(() => {});
    }

    sseEmitter?.next({
      event: 'error',
      data: { message: `Report generation failed: ${message}`, phase: 'reporting' },
    });
    sseEmitter?.complete();

    return { errors: [`Report agent error: ${message}`] };
  }
}

// ============================================================
// HELPER FUNCTIONS
// ============================================================

function computeConfidenceScore(
  financial: financialOutput,
  news: newsOutput,
  competitive: competitiveOutput,
  thesis: thesisOutput,
  evidenceCount: number,
): ConfidenceScore {
  const financialDataQuality = financial
    ? financial.hasDataGap ? 60 : 90
    : 20;

  const newsCoverage = news
    ? news.hasDataGap ? 40 : Math.min(90, 50 + news.articles.length * 5)
    : 20;

  const competitiveAnalysis = competitive
    ? competitive.hasDataGap ? 45 : Math.min(85, 50 + competitive.competitors.length * 7)
    : 20;

  const thesisCoherence = thesis ? 80 : 20;

  const citationDensity = Math.min(90, evidenceCount * 8);

  const overall = Math.round(
    financialDataQuality * 0.30 +
    newsCoverage * 0.20 +
    competitiveAnalysis * 0.20 +
    thesisCoherence * 0.20 +
    citationDensity * 0.10,
  );

  const breakdown = {
    financialDataQuality,
    newsCoverage,
    competitiveAnalysis,
    thesisCoherence,
    citationDensity,
  };

  const gaps = [];
  if (!financial || financial.hasDataGap) gaps.push('incomplete financial data');
  if (!news || news.hasDataGap) gaps.push('limited news coverage');
  if (!competitive || competitive.hasDataGap) gaps.push('limited competitive data');
  if (!thesis) gaps.push('thesis generation failed');

  const rationale = gaps.length > 0
    ? `Confidence reduced due to: ${gaps.join(', ')}. Available data is ${overall >= 70 ? 'sufficient' : 'limited'} for the analysis.`
    : `High confidence — complete data available across all dimensions with ${evidenceCount} evidence points.`;

  return { overall, breakdown, rationale };
}

function compileCitations(
  evidence: Evidence[],
  financial: financialOutput,
  news: newsOutput,
  company: any,
): Citation[] {
  const seen = new Set<string>();
  const citations: Citation[] = [];

  // 1. Add Screener.in as a primary financial source if available
  const cleanTicker = (company.ticker || company.nseCode || '').trim().toUpperCase().replace(/[^A-Z0-9_-]/g, '');
  if (cleanTicker) {
    const screenerUrl = `https://www.screener.in/company/${cleanTicker}/`;
    seen.add(screenerUrl);
    citations.push({
      displayId: '',
      title: `Screener.in — ${company.companyName} Financials & Ratios`,
      sourceName: 'Screener.in',
      url: screenerUrl,
      citationType: 'financial_data',
      accessedAt: new Date().toISOString(),
    });
  }

  const webCandidates: Citation[] = [];
  const indianApiCandidates: Citation[] = [];

  // Helper to categorize and push
  const addCandidate = (url: string, title: string, sourceName: string, type: 'news_article' | 'financial_data') => {
    const cleanedUrl = url.trim();
    if (!cleanedUrl || seen.has(cleanedUrl.toLowerCase())) return;
    seen.add(cleanedUrl.toLowerCase());

    const citation: Citation = {
      displayId: '',
      title,
      sourceName,
      url: cleanedUrl,
      citationType: type,
      accessedAt: new Date().toISOString(),
    };

    if (cleanedUrl.toLowerCase().includes('indianapi.in') || cleanedUrl.toLowerCase().includes('indianapi.co')) {
      indianApiCandidates.push(citation);
    } else {
      webCandidates.push(citation);
    }
  };

  // 2. Collect from news articles
  if (news) {
    news.articles.forEach((article: AnalyzedArticle) => {
      if (article.url) {
        addCandidate(
          article.url,
          article.title || 'News Article',
          article.source || 'News Source',
          'news_article',
        );
      }
    });
  }

  // 3. Collect from evidence pool
  evidence.forEach((e) => {
    if (e.sourceUrl) {
      addCandidate(
        e.sourceUrl,
        e.sourceName || e.evidenceType.replace('_', ' '),
        e.sourceName || e.sourceAgent,
        e.evidenceType.includes('news') ? 'news_article' : 'financial_data',
      );
    }
  });

  // 4. Add IndianAPI primary stock profile to IndianAPI candidates
  if (financial && !financial.hasDataGap) {
    const indianApiProfileUrl = `https://stock.indianapi.in/stock?name=${encodeURIComponent(company.companyName)}`;
    addCandidate(
      indianApiProfileUrl,
      `IndianAPI — ${company.companyName} Stock Profile`,
      'IndianAPI',
      'financial_data',
    );
  }

  // 5. Build final citation list ensuring >= 75% web citations (ratio: W / (W+I) >= 0.75 => I <= W / 3)
  const MAX_CITATIONS = 15;

  // Add web candidates up to MAX_CITATIONS - 1 (since Screener.in is already added as a web source)
  const webToTake = webCandidates.slice(0, MAX_CITATIONS - citations.length);
  citations.push(...webToTake);

  // Take IndianAPI candidates based on ratio
  const w = citations.length; // Number of web citations currently in list
  const maxI = Math.floor(w / 3);
  const indianApiToTake = indianApiCandidates.slice(0, Math.min(maxI, MAX_CITATIONS - citations.length));
  citations.push(...indianApiToTake);

  // Assign display IDs sequentially
  citations.forEach((c, index) => {
    c.displayId = `[${index + 1}]`;
  });

  return citations;
}

function buildConfidenceSectionMarkdown(
  score: ConfidenceScore,
  gaps: string[],
): string {
  const { overall, breakdown, rationale } = score;
  const scoreEmoji = overall >= 80 ? '🟢' : overall >= 60 ? '🟡' : '🔴';

  return `## Confidence Score & Data Quality

### Overall Confidence: ${scoreEmoji} ${overall}/100

${rationale}

### Score Breakdown

| Dimension | Score | Notes |
|-----------|-------|-------|
| Financial Data Quality | ${breakdown.financialDataQuality}/100 | IndianAPI real-time & financial statements |
| News Coverage | ${breakdown.newsCoverage}/100 | IndianAPI news + Tavily + Exa search |
| Competitive Analysis | ${breakdown.competitiveAnalysis}/100 | IndianAPI peer list & industry comparison |
| Thesis Coherence | ${breakdown.thesisCoherence}/100 | Evidence-backed synthesis |
| Citation Density | ${breakdown.citationDensity}/100 | Sources per claim |

${gaps.length > 0 ? `### ⚠️ Data Gaps\n\n${gaps.map((g) => `- ${g}`).join('\n')}` : '### ✅ No significant data gaps identified'}

### Disclaimer

*${FINANCIAL_DISCLAIMER}*`;
}

function buildCitationsSectionMarkdown(citations: Citation[]): string {
  if (citations.length === 0) {
    return '## Source Citations\n\nNo citations available.';
  }

  const citationLines = citations
    .map((c) => `${c.displayId} **${c.title}**  \n   *${c.sourceName}* — [${c.url}](${c.url})`)
    .join('\n\n');

  return `## Source Citations

${citationLines}

---
*All financial data sourced from IndianAPI. News data sourced from IndianAPI news feed, Tavily, and Exa. Report generated by ResearchGPT AI system.*`;
}

function alignCitations(content: string, citations: Citation[]): string {
  if (!content) return content;

  // Regex to match markdown links: [Text](URL)
  const markdownLinkRegex = /\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g;

  return content.replace(markdownLinkRegex, (match, text, url) => {
    const cleanUrl = url.trim();

    // Find index of URL in citations (case-insensitive)
    let citationIndex = citations.findIndex(
      (c) => c.url.toLowerCase() === cleanUrl.toLowerCase()
    );

    if (citationIndex === -1) {
      // URL not in compileCitations list (perhaps added dynamically by an agent)
      // Add it so it displays in the final list
      let domain = 'Source';
      try {
        domain = new URL(cleanUrl).hostname.replace('www.', '');
      } catch {
        // Fallback
      }

      const newCitation: Citation = {
        displayId: `[${citations.length + 1}]`,
        title: text || `Source — ${domain}`,
        sourceName: domain,
        url: cleanUrl,
        citationType: 'news_article',
        accessedAt: new Date().toISOString(),
      };
      citations.push(newCitation);
      citationIndex = citations.length - 1;
    }

    const displayIndex = citationIndex + 1;

    // If the text is already a number/citation like "1" or "[1]", just output the citation link
    if (/^\[?\d+\]?$/.test(text.trim())) {
      return `[${displayIndex}](${cleanUrl})`;
    }

    // Otherwise, keep the text and append the superscript citation link
    return `${text} [${displayIndex}](${cleanUrl})`;
  });
}

type financialOutput = FinancialAgentOutput | null | undefined;
type newsOutput = NewsAgentOutput | null | undefined;
type competitiveOutput = CompetitiveAgentOutput | null | undefined;
type thesisOutput = ThesisAgentOutput | null | undefined;
